// import initSmoothScroll from './modules/scroll-suave.js';
import initiAnimateScroll from './modules/initiAnimateScroll.js';
import initAccordion from './modules/initAccordion.js';
import initTabNav from './modules/initTabNav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdown from './modules/dropdown.js';
import menuMobile from './modules/menuMobile.js';
import funcionamento from './modules/funcionamento.js';
import fetchAnimais from './modules/fetchAnimais.js';
import fetchBitcoin from './modules/fetchBitcoin.js';

// initSmoothScroll();
initiAnimateScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropdown();
menuMobile();
funcionamento();
fetchAnimais();
// fetchBitcoin();
